### ISSUE TITLE
Redirect to home page in 404.html and add 'profile not found page'

### ISSUE THREAD

**Issue by Rafisto** [Rafisto/englishnow#1]
### Redirect to home page in 404.html 
- [x] Inside 404.html there is a line of code representing a button, which should redirect to a homepage:
```html
49| <p><a class="learnbutton" href="../" role="button">Powrót do strony głównej</a></p>
```
Although at first the code may seem to work just fine, there is one major issue regarding the link complexity.
In case a website path, as the one below, consists of more than a single subpath, the code results in:
`/13409/21342341/23412341234/` --> `/13409/21342341/` 
whereas the desired output is be just `/` given any of the aforementioned paths is nonexistent.
### Add 'profile not found' page
- [x] There ought to be another 404 template especially designed to inform about nonexistent user profile or that the profile has been banned or removed.

**Comment by Rafisto** [comment]
{{ url_for('index') }} is a direct template for flask to redirect to the absolute path. First paragraph resolved. Changing the issue label to far away, as its not possible to resolve second part of the issue without fetching username list from the database.

**Comment by ModerNews** [comment]
> Inside 404.html there is a line of code representing a button, which should redirect to a homepage [...]

Replaced `{{ url_for("index") }}` with absolute path `"/"` in newest commit, due to splitting app.py into modules, if we want to stick with `url_for`, this will need to be adjusted to new site map

**Comment by Rafisto** [comment]
```py
elif current_app.database.get_user_by_username(username) is not None:
    return render_template('profile.html', username=username)
```
from_tuple in models.py now has a statement to handle an exceptional case of data being None type
it does not throw an error anymore, gruzin @ModerNews 
```py
if data is None:
    return None
```
