### ISSUE TITLE
User dashboard

### ISSUE THREAD

**Issue by ModerNews** [Rafisto/englishnow#12]
Custom header for when user is logged in

- [x] Logout button redirecting to POST /logout
- [x] Dashboard button redirecting to GET /profile/me

**Comment by ModerNews** [comment]
Current user is available through `user` variable in jinja, it also has `is_authenticated()` and `is_active()` methods for checking user state

**Comment by Rafisto** [comment]
Finished dropdown menu:
![obraz](https://user-images.githubusercontent.com/88141065/166645869-e1979bba-67bf-4209-a8e1-73c0f1fc1ecc.png)
![obraz](https://user-images.githubusercontent.com/88141065/166645971-da01f780-6f8a-4b31-aae1-7d4d47dbfe76.png)
