### ISSUE TITLE
Blogpost markdown to html

### ISSUE THREAD

**Issue by Rafisto** [Rafisto/englishnow#15]
Webpage articles are easy to write using markdown
- [x] Create a script that compiles markdown to HTML
- [x] Create a scss styling solely to beautify blogposts
- [ ] #31
- [x] Create an endpoint to show article preview in debug mode 
Let from now on make all debug endpoints have /debug/### as their base link
Changes will include terror function

**Comment by ModerNews** [comment]
Could we get script alone commited?

**Comment by Rafisto** [comment]
Sure, here it is

**Comment by Rafisto** [comment]
Due to the security reasons mentioned in one of the previous commit messages, Markdown to HTML will from now on work client-side. The approach will also lower the computational requirements, as the server will no longer be responsible for converting Markdown to HTML. Not only will it help with the aformentioned case, but also it will ease the preview enhancement creation.

**Comment by Rafisto** [comment]
![obraz](https://user-images.githubusercontent.com/88141065/174482525-bb761d36-029a-4197-b352-47ab56d179e6.png)
![obraz](https://user-images.githubusercontent.com/88141065/174482527-6b6fb4e3-d685-41f3-9c14-2be140cd1b24.png)

**Comment by Rafisto** [comment]
introducing a new tabview
preview functionality has been integrated with writeup.html to create a simple tab view
