### ISSUE TITLE
401 and 403 webpages

### ISSUE THREAD

**Issue by ModerNews** [Rafisto/englishnow#2]
Create webpages signalizing:

- [ ]  HTTP error 401 - missing authorization token
- [ ]  HTTP error 403 - access denied with current authorization level

**Comment by Rafisto** [comment]
I will resolve the issue today.

**Comment by Rafisto** [comment]
I considered and resolved the problem globally, which now allows to display any error code included in `HTTPErrorCodes.py`
### New error display system
#### Usage
##### Basic usage
In case of triggering an error exception use the following approach. Let `<code>` be the the string of an error. To display an error write the code below:
```py
code = <code>
return render_template('error.html', error=Error.HTTPErrorCodes.getCodeText(code))
```
- `<code>` has to be a string
##### Example to generate error 401
Suppose for whatever reason user has generated an HTTP error with the code 401. Then use this code to display the following:
```py
return render_template('error.html', error=Error.HTTPErrorCodes.getCodeText('401'))
```
##### Adding a new error code
To add a new error code response modify the dictionary error_codes inside HTTPErrorCodes.py to contain the following information:
```
'<code>':
[
    '<title>',
    '<message>',
    '<icon src>'
],
```
Example:
```
'-1':
[
    '-1 Kod błędu nie istnieje',
    'Zaistniały błąd nie istnieje w bazie błędów',
    '/static/images/bootstrap-icons-1.8.1/exclamation-square.svg'
],
```
### Terror - Test Error
While in the debug mode it is possible to check how does the template render look like in browser.
To access terror include the following path into the browser: `/terror/<code>`, where `<code>` is the desired error code
![obraz](https://user-images.githubusercontent.com/88141065/164913560-fff69afe-4ef8-485b-a1a1-b5baae3dba98.png)
