### ISSUE TITLE
Registration warnings

### ISSUE THREAD

**Issue by ModerNews** [Rafisto/englishnow#20]
In-page warnings about double values next to input fields on registration page
- [x] Username
- [x] Email

**Comment by ModerNews** [comment]
Those will be easily accessible through `wrong_email` and `wrong_username` parameters in template

**Comment by Rafisto** [comment]
Added two additional crud functions as follows to check possible duplication of email or username.
```py
def check_repeated_email(self, email):
    """
    Checks if given email already exists in the database
    :param: email, string
    :return: True if email exists, else false
    :rtype: bool
    """
    with self._connection.cursor() as cursor:
        cursor.execute('SELECT 1 FROM USERS WHERE email = %s LIMIT 1', email)
        if cursor.fetchone() is None:
            return False
        return True
```
Then the function is called in login.py:
```py
if current_app.database.check_repeated_email(temp_form.inputEmail.data):
    return render_template('register.html', form=temp_form, wrong_email=True)
```
The function is now also used in settings.py:
```py
if new_username not in [user.username for user in current_app.database.get_users()]:
```
has been changed to:
```
if not current_app.database.check_repeated_username(new_username):
```
as due to `LIMIT 1` part in the SQL query the code does not need to iterate through all users, but only to the first occurence.

**Comment by Rafisto** [comment]
![obraz](https://user-images.githubusercontent.com/88141065/168470294-fe6dc2f3-c21c-4aa9-9331-100e826cd30a.png)

**Comment by ModerNews** [comment]
Made changes to prevent generating webpage response on POST method
